Actually use the sdl-config binary that we found when configuring
angband/angband pull request #5099
Opened 2021-10-16 14:06 UTC by timschumi

This is helpful when cross-compiling or when choosing an SDL prefix that is not in the default path.

2021-10-17 22:35 UTC, timschumi commented
So the statistics build is enabling `sdl-mixer` without enabling SDL as a whole. Is that intended? Or should we add SDL to the enabled options for that build?

2021-10-18 00:39 UTC, backwardsEric commented
Yes, the statistics build uses --sdl-mixer without --enable-sdl to check that including sound support (via SDL) but not the full SDL front-end works.  Invoking AM_PATH_SDL just before setting SDL_CFLAGS for the mixer (i.e. line 411) and AM_PATH_SDL2 just before setting SDL2_CFLAGS for the mixer (i.e. line 388) should resolve the failed check.

2021-11-24 16:35 UTC, backwardsEric requested changes
Thanks for finding this; it's a definite improvement to how the configuration was being handled.  To fix the the problem with the statistics build, incorporate calls to the AM_PATH_SDL() and AM_PATH_SDL2() macros at the points where, respectively, the SDL and SDL2 mixers are set up.  This, https://github.com/backwardsEric/angband/commit/92bfabd0def640d46b39601676654d20a83fec78 , is what works for me.  With that modification (or something like it), this should be fine for incorporation into the master branch.

2021-11-24 16:47 UTC, timschumi commented
I originally had the plan to fix it properly (i.e. determine which libraries are needed beforehand, query sdl-config once, etc., since having multiple copies of everything isn't that great), but I had less time to spend on this then expected, so I just put it into a draft state and let it sit there.

I guess I'll just pick over your patch for now, to prevent this from being "WIP" equally long as my other PRs were, and since I don't want to miss the next release to get the actual issue fix in.

2021-11-24 17:34 UTC, backwardsEric approved these changes
Yes, doing the configuration once would be better; getting this good incremental improvement out the door is fine for now.

2021-11-24 17:34 UTC, merged